name: 🐛 Bug Report
description: Report a bug or unexpected behavior in Quark
title: "[BUG] "
labels: ["✅ needs testing"]
body:
  - type: markdown
    attributes:
      value: |
        # 🐛 Bug Report
        
        Thank you for taking the time to report a bug! Please fill out the information below to help us understand and reproduce the issue.
        
        ---

  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting your bug report
      options:
        - label: I have searched for existing issues and this is not a duplicate
          required: true
        - label: I am using the latest version of Quark
          required: true

  - type: textarea
    id: bug-description
    attributes:
      label: 🔍 Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened and what you expected to happen instead
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 🔄 Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Initialize LibraryManager with '...'
        2. Load dependency '...'
        3. Call method '...'
        4. See error
      value: |
        1. 
        2. 
        3. 
        4.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: ✅ Expected Behavior
      description: What did you expect to happen?
      placeholder: A clear and concise description of what you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: ❌ Actual Behavior
      description: What actually happened?
      placeholder: A clear and concise description of what actually happened
    validations:
      required: true

  - type: textarea
    id: code-sample
    attributes:
      label: 💻 Code Sample
      description: Please provide a minimal code sample that reproduces the issue
      render: java
      placeholder: |
        // Minimal code sample that reproduces the issue
        BukkitLibraryManager libraryManager = new BukkitLibraryManager(this);
        libraryManager.addGoogleMavenCentralMirror();
        
        libraryManager.loadDependency(
            Dependency.builder()
                .groupId("com.example")
                .artifactId("example")
                .version("1.0.0")
                .build()
        );
    validations:
      required: false

  - type: textarea
    id: error-logs
    attributes:
      label: 📝 Error Logs / Stack Trace
      description: If applicable, add error logs or stack traces
      render: text
      placeholder: |
        [ERROR] Failed to load dependency: com.example:example:1.0.0
        java.lang.RuntimeException: Cannot resolve version for dependency: com.example:example
            at org.bxteam.quark.resolver.DependencyResolver.resolveDependencyVersion(DependencyResolver.java:123)
            ...
    validations:
      required: false

  - type: dropdown
    id: platform
    attributes:
      label: 🎯 Platform
      description: Which platform are you using?
      options:
        - Bukkit/Spigot
        - Paper
        - BungeeCord/Waterfall
        - Velocity
      default: 0
    validations:
      required: true

  - type: input
    id: platform-version
    attributes:
      label: 📋 Platform Version
      description: What version of the platform are you running?
      placeholder: "e.g., Paper 1.21.4, BungeeCord 1.21-R0.1-SNAPSHOT, Java 17"
    validations:
      required: true

  - type: input
    id: quark-version
    attributes:
      label: 🏷️ Quark Version
      description: What version of Quark are you using?
      placeholder: "e.g., 2.0.0, 1.5.3"
    validations:
      required: true

  - type: input
    id: java-version
    attributes:
      label: ☕ Java Version
      description: What version of Java are you running?
      placeholder: "e.g., OpenJDK 17.0.2, Oracle JDK 11.0.16"
    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: 💻 Operating System
      description: What operating system are you running?
      options:
        - Windows
        - macOS
        - Linux (Ubuntu/Debian)
        - Linux (CentOS/RHEL)
        - Linux (Arch)
        - Linux (Other)
        - Other
      default: 0
    validations:
      required: false

  - type: textarea
    id: dependency-info
    attributes:
      label: 📦 Dependency Information
      description: Information about the dependency that's causing issues (if applicable)
      placeholder: |
        - Group ID: com.example
        - Artifact ID: example
        - Version: 1.0.0
        - Repository: Maven Central
        - Relocations: com.example -> org.myproject.libs.example
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: 📋 Additional Context
      description: Add any other context about the problem here
      placeholder: |
        Any additional information that might help us understand the issue:
        - Network configuration
        - Firewall settings
        - Corporate proxy
        - Custom repositories
        - Other plugins/dependencies
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        
        **Thank you for your bug report!** 🙏
        
        Our team will review this issue and may ask for additional information. If this is an urgent issue affecting production, please mention it in the additional context section.