package org.bxteam.quark.gradle

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction

/**
 * Writes the dependency manifest read by `LibraryManager#loadFromGradle()` to `META-INF/quark/manifest`.
 */
@CacheableTask
abstract class GenerateQuarkManifest : DefaultTask() {
    /** Repository URLs, in lookup order. */
    @get:Input
    abstract val repositories: ListProperty<String>

    /** Dependency coordinates (`group:artifact:version[:classifier]`). */
    @get:Input
    abstract val dependencies: ListProperty<String>

    /** Relocations as `pattern=relocatedPattern`. */
    @get:Input
    abstract val relocations: ListProperty<String>

    /** Resource root the manifest is written to. */
    @get:OutputDirectory
    abstract val outputDirectory: DirectoryProperty

    @TaskAction
    fun generate() {
        val text = buildString {
            append("# Quark dependency manifest, generated by the Quark Gradle plugin\n")
            append("format=").append(MANIFEST_FORMAT).append('\n')
            section("repositories", repositories.get().distinct())
            section("dependencies", dependencies.get().distinct())
            section("relocations", relocations.get())
        }

        val file = outputDirectory.file(MANIFEST_PATH).get().asFile
        file.parentFile.mkdirs()
        file.writeText(text)
    }

    private fun StringBuilder.section(name: String, lines: List<String>) {
        append('\n').append('[').append(name).append("]\n")
        lines.forEach { append(it).append('\n') }
    }

    internal companion object {
        const val MANIFEST_PATH = "META-INF/quark/manifest"
        const val MANIFEST_FORMAT = 1
    }
}
