name: Set Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to set'
        required: true
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  set-version:
    name: Set Version
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}

      - name: Set Version
        run: |
          sed -i 's/^version=.*/version='"${{ inputs.version }}"'/g' gradle.properties

      - name: Update QuarkPlugin Version
        run: |
          sed -i 's/private const val QUARK_VERSION: String = ".*"/private const val QUARK_VERSION: String = "${{ inputs.version }}"/g' gradle-plugin/src/org/bxteam/quark/gradle/QuarkPlugin.kt

      - name: Update Gradle Plugin Version
        run: |
          sed -i 's/^version = ".*"/version = "${{ inputs.version }}"/g' gradle-plugin/build.gradle.kts

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: 'chore(release): bump version to ${{ inputs.version }}'